### ISSUE TITLE
YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager

### ISSUE THREAD

**Issue by larffxx** [lavalink-devs/lavaplayer#92] opened 2024-03-31 16:53 UTC
No exception but: "YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions." message

**Comment by larffxx** [comment] 2024-03-31 16:56
and lavaplayer stops work after this WARN

**Comment by devoxin** [comment] 2024-03-31 17:09
A warning is not an error. It's just notifying you that it can't retrieve an [account] auth token because you haven't provided account credentials. This is a non-issue, and most likely unrelated to why your Lavaplayer stops working. I would enable debug logs and post them.

**Comment by larffxx** [comment] 2024-03-31 17:30
Printed stack trace and find exception "com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Video returned by YouTube isn't what was requested" using slash command with jda

**Comment by devoxin** [comment] 2024-03-31 17:32
Duplicate of #84 #85 #89

**Closed by devoxin** 2024-03-31 17:32 UTC
