### ISSUE TITLE
Issue decoding mp3s with frame size 961

### ISSUE THREAD

**Issue by awesomekosm** [lavalink-devs/lavaplayer#36] opened 2023-09-13 23:31 UTC
Some MP3s fail to load, their frame length is 961. 

For example, the same mp3 is fine when played through browser or Elisa music player.

I can provide mp3 to reproduce.

```
2023-09-13 18:22:26.886  WARN 1 --- [ader-8-thread-1] c.s.d.l.c.MediaContainerDetection        : Attempting to detect file with container mp3 failed.

java.lang.IndexOutOfBoundsException: Range [4, 4 + 1040) out of bounds for length 961
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[na:na]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Unknown Source) ~[na:na]
        at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Unknown Source) ~[na:na]
        at java.base/java.util.Objects.checkFromIndexSize(Unknown Source) ~[na:na]
        at java.base/java.io.DataInputStream.readFully(Unknown Source) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.fillFrameBuffer(Mp3FrameReader.java:121) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.initialiseSeeker(Mp3TrackProvider.java:92) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:87) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:57) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:92) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:77) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:59) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:58) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:41) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175) ~[lavaplayer-2.0.1.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-09-13 18:22:26.891 ERROR 1 --- [ader-8-thread-1] com.bots.shura.audio.AudioLoader         : LavaPlayer could not parse an audio source for some reason

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:35) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:41) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-2.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175) ~[lavaplayer-2.0.1.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```

**Comment by Jacrispys** [comment] 2023-09-24 22:47
Having the same issue, is this working in another version?

**Comment by melike2d** [comment] 2023-09-24 23:39
This is probably an issue that was caused by Mp3 being changed in the 2.0.1 release to support more MPEG versions (cc @markozajc)

**Comment by markozajc** [comment] 2023-09-24 23:43
That's correct.

**Comment by topi314** [comment] 2023-09-27 11:12
released in https://github.com/lavalink-devs/lavaplayer/releases/tag/2.0.2

**Closed by topi314** 2023-09-27 11:12 UTC
