### ISSUE TITLE
Youtube Visitor ID was recently updated, not updating again right away

### ISSUE THREAD

**Issue by Hacker6329** [lavalink-devs/lavaplayer#83] opened 2024-03-29 23:11 UTC
I was using lavaplayer for my own discord bot to play youtube into my server and when I put a valid youtube link it started playing the track, after some time it suddenly stopped playing the track and in the console started spamming this message:

DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker -- YouTube visitor id was recently updated, not updating again right away.

Sometimes when i provide a valid link it response back with this message without playing anything:
DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor -- Common failure for playback of mvkcyB_lve0: Video returned by YouTube isn't what was requested

**Comment by topi314** [comment] 2024-03-29 23:12
Duplicate of https://github.com/lavalink-devs/lavaplayer/issues/82

**Comment by Hacker6329** [comment] 2024-03-29 23:12
I forgot to say that I'm using the latest available build and before today my bot worked perfectly.

**Closed by topi314** 2024-03-29 23:12 UTC
