### ISSUE TITLE
Common Failure: Video returned by Youtube isn't what was requested.

### ISSUE THREAD

**Issue by Acareld** [lavalink-devs/lavaplayer#91] opened 2024-03-31 09:28 UTC
After working for a good amount of time, my bot now stopped playing youtube links or search requests. I configured logback to debug level and got this log: 

`120 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider - Performing a search with query in the end
11:21:17.501 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Sending voice request {"op":4,"d":{"self_deaf":false,"guild_id":947823451253641256,"channel_id":947823451253641260,"self_mute":false}}
11:21:17.914 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider - Attempting to parse results from search page
11:21:17.914 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Loaded a playlist with identifier ytsearch: in the end using YoutubeAudioSourceManager.
addedTrack
11:21:17.914 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackStartEvent
11:21:17.915 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Starting to play track eVTXPUF4Oz4 locally with listener com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer@1826b9ce
11:21:17.915 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader - Loading track info with payload: {"context":{"thirdParty":{"embedUrl":"https://google.com"},"client":{"screenPixelDensity":1,"androidSdkVersion":30,"screenWidthPoints":1920,"clientName":"ANDROID","screenHeightPoints":1080,"screenDensityFloat":1,"clientScreen":"EMBED","clientVersion":"18.06.35"}},"racyCheckOk":true,"contentCheckOk":true,"videoId":"eVTXPUF4Oz4","params":"CgIQBg","playbackContext":{"contentPlaybackContext":{"signatureTimestamp":"19809"}}}
11:21:17.915 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker - YouTube visitor id was recently updated, not updating again right away.
11:21:18.099 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Common failure for playback of eVTXPUF4Oz4: Video returned by YouTube isn't what was requested
11:21:18.099 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackExceptionEvent
11:21:18.162 [JDA RateLimit-Elastic-Worker 3] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [86cf44b49a2e5b24-VIE]
11:21:18.999 [JDA [0 / 1] AudioWS-ReadThread (guildId: 947823451253641256)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Using encryption mode xsalsa20_poly1305_lite
11:21:19.031 [JDA [0 / 1] AudioWS-ReadThread (guildId: 947823451253641256)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Unknown Audio OP code.
{"op":18,"d":{"user_id":"238371252014678016","flags":2}}
11:21:19.032 [JDA [0 / 1] AudioWS-ReadThread (guildId: 947823451253641256)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Unknown Audio OP code.
{"op":20,"d":{"user_id":"238371252014678016","platform":0}}
11:21:19.464 [JDA [0 / 1] AudioWS-ReadThread (guildId: 947823451253641256)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Audio connection has finished connecting!
11:21:19.465 [JDA [0 / 1] AudioConnection Guild: 947823451253641256 Sending Thread] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackEndEvent
11:21:19.532 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Sending voice request {"op":4,"d":{"self_deaf":false,"guild_id":"947823451253641256","channel_id":null,"self_mute":false}}
11:21:29.286 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader - Loading track info with payload: {"context":{"thirdParty":{"embedUrl":"https://google.com"},"client":{"screenPixelDensity":1,"androidSdkVersion":30,"screenWidthPoints":1920,"clientName":"ANDROID","screenHeightPoints":1080,"screenDensityFloat":1,"clientScreen":"EMBED","clientVersion":"18.06.35"}},"racyCheckOk":true,"contentCheckOk":true,"videoId":"E_39Fgq9hfk","params":"CgIQBg","playbackContext":{"contentPlaybackContext":{"signatureTimestamp":"19809"}}}
11:21:29.286 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker - YouTube visitor id was recently updated, not updating again right away.
11:21:29.384 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Common failure for loading item https://www.youtube.com/watch?v=E_39Fgq9hfk: Video returned by YouTube isn't what was requested`

Currently im running it on a RaspberryPi4, but the results dont change on my windows machine.

**Comment by duncte123** [comment] 2024-03-31 09:36
Duplicate of https://github.com/lavalink-devs/lavaplayer/issues/89

**Closed** 2024-03-31 09:47 UTC
